apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-alert-deployment
  labels:
    app: stock-alert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-alert
  template:
    metadata:
      labels:
        app: stock-alert
    spec:
      containers:
        - name: stock-alert
          image: sivasakthim2322/stock-alert-app:latest
          imagePullPolicy: Always

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: stock-alert-service
spec:
  type: NodePort
  selector:
    app: stock-alert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008



      Online Ticket Cancellation System
Problem Statement:
Ensure tickets are cancelled and refunded correctly.
Tasks:
1. Develop cancellation and refund logic
2. Write JUnit tests for refund scenarios
3. Implement CI/CD pipeline with automated testing
➢ Set up version control using GitHub
➢ Configure CI pipeline (e.g., Jenkins/GitHub Actions) to trigger on code commits
➢ Automate build process using Maven
➢ Integrate automated unit tests in pipeline
➢ Configure CD pipeline for automatic deployment to staging/production
4. Deploy services on Docker and Kubernetes
➢ Containerize application using Docker (write Dockerfile)
➢ Build and push Docker image to container registry (Docker Hub)
➢ Create Kubernetes deployment and service YAML files
